# Generated by Django 4.2.5 on 2023-09-21 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.TextField(blank=True, null=True)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('status', models.CharField(default='On-going', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('published_time', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(default=5.0)),
            ],
        ),
        migrations.CreateModel(
            name='NovelGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.genre')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.novel')),
            ],
            options={
                'unique_together': {('novel', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='NovelAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.author')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.novel')),
            ],
            options={
                'unique_together': {('novel', 'author')},
            },
        ),
        migrations.AddField(
            model_name='novel',
            name='authors',
            field=models.ManyToManyField(through='web.NovelAuthor', to='web.author'),
        ),
        migrations.AddField(
            model_name='novel',
            name='genres',
            field=models.ManyToManyField(through='web.NovelGenre', to='web.genre'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'index_together': {('novel', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('path', models.TextField(unique=True)),
                ('chapter_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.novel')),
            ],
            options={
                'index_together': {('novel', 'chapter_number')},
            },
        ),
    ]
